"""migration 1

Revision ID: ed44e0b47a1b
Revises: 
Create Date: 2021-11-08 01:10:28.634327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed44e0b47a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comercio',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('email_contacto', sa.String(length=50), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=15), nullable=True),
    sa.Column('api_key', sa.String(length=36), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('empleado',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('apellidos', sa.String(length=40), nullable=True),
    sa.Column('pin', sa.String(length=6), nullable=True),
    sa.Column('comercio', sa.BigInteger(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['comercio'], ['comercio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empleado')
    op.drop_table('comercio')
    # ### end Alembic commands ###
